def display_name(code: str) -> str:
    return {
        "VI": "Vintage",
        "LE": "Legacy",
        "MO": "Modern",
        "PI": "Pioneer",
        "EX": "Extended",
        "HI": "Historic",
        "ST": "Standard",
        "BL": "Block",
        "PAU": "Pauper",
        "cEDH": "cEDH",
        "EDH": "Duel Commander",
        "EDHM": "MTGO Commander",
        "EXP": "Explorer",
        "HIGH": "Highlander",
        "CHL": "Canadian Highlander",
        "PEA": "Peasant",
        "ALCH": "Alchemy",
        "PREM": "Premodern",
        "LI": "Limited",
        "CPOP": "Cube Popularity",
        "CELO": "Cube Elo",
    }[code]
